### ISSUE TITLE
Travis: Rate limit exceeded

### ISSUE THREAD

**Issue by schnittstabil** [SamVerschueren/dev-time#11]
I'm pretty sure you know how to deal with it :smile: 

Notes: https://github.com/travis-ci/travis-ci/issues/4195#issuecomment-145370438

**Comment by SamVerschueren** [comment]
That's odd, it was added to the settings.

![screen shot 2016-02-18 at 13 15 23](https://cloud.githubusercontent.com/assets/1913805/13143084/b8fb188e-d641-11e5-95f3-750257537ac9.png)

**Comment by SamVerschueren** [comment]
Ok, it seems that PR's don't receive those (which is odd).

**Comment by stevemao** [comment]
It happens to my repo too :disappointed: https://github.com/conventional-changelog/conventional-github-releaser/pull/16
