### ISSUE TITLE
Cache the timezone

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/dev-time#3]
For a day.

Always use the cache when offline.

**Comment by SamVerschueren** [comment]
Is there a way to do this easily or should I just write it into a `~/.dev-time` file with for example the following content.

``` json
{
    "sindresorhus": "2015-12-08T08:08:35+01:00",
    "SamVerschueren": "2015-12-08T07:08:35+01:00"
}
```

If a call is made, read the value of the `user`, if it does not exist or it is an older value, retrieve a new value and update the `~/.dev-time` file.

**Comment by sindresorhus** [comment]
You could use `configstore`.

**Comment by SamVerschueren** [comment]
Aha, thanks! :)

**Comment by SamVerschueren** [comment]
@sindresorhus Should I add a `cache` option that can force the module to not use the cache if set to `false`?

**Comment by sindresorhus** [comment]
@SamVerschueren I would personally wait until someone request it with a good use-case.

**Comment by SamVerschueren** [comment]
:+1:
